#!env python
import os
import curses
import argparse
import configparser
import feedparser

def interface(scr):
    scr.clear()
    scr.refresh()
    curses.start_color()
    curses.use_default_colors()

    curses.init_pair(1, curses.COLOR_CYAN, -1)
    curses.init_pair(2, curses.COLOR_MAGENTA, -1)
    curses.init_pair(3, curses.COLOR_YELLOW, -1)

    key_input = 0

    while (key_input != ord('Q')):

        # Initialization
        scr.clear()
        curses.curs_set(0)
        height, width = scr.getmaxyx()
        playerwidth = 4
        height = height - playerwidth

        vert_divider = width // 3

        # window to hold podcast list
        podlist = scr.subwin(height,vert_divider,0,0)

        # list of episodes for each podcast
        epslist = scr.subwin(height // 2, width - vert_divider, 0, vert_divider)

        # episode summary information
        desclist = scr.subwin(height - height // 2, width - vert_divider, height // 2, vert_divider)

        podlist.attron(curses.color_pair(1))
        podlist.box(0,0)
        podlist.addstr(0,1," podcasts ")
        podlist.attroff(curses.color_pair(1))

        epslist.attron(curses.color_pair(2))
        epslist.box(0,0)
        epslist.addstr(0,1," episodes ")
        epslist.attroff(curses.color_pair(2))

        desclist.attron(curses.color_pair(3))
        desclist.box(0,0)
        desclist.addstr(0,1," episode description ")
        desclist.attroff(curses.color_pair(3))


        scr.refresh()
        key_input = scr.getch()

def feedfetcher(url):
    d = feedparser.parse(url)
    return d

def main():
    env = {}
    parser = argparse.ArgumentParser(description="A curses-based podcatcher")
    parser.add_argument("-c", "--config", help="use this config file instead")
    args = parser.parse_args()
    config = configparser.ConfigParser()

    d = feedfetcher('https://feedpress.me/ReasonAudio')
    print(d['feed']['summary'])

# Let's figure out where the hell our config file is hiding
    conffile = os.path.expanduser('~/.config/potsy/potsy.conf')
    if os.path.isfile(args.config) :
        conffile = args.config
    elif 'XDG_CONFIG_HOME' in os.environ :
        p = os.path.join(os.environ['XDG_CONFIG_HOME'],"potsy/potsy.conf")
        if os.path.isfile(p) :
            conffile = p
    config.read(conffile)

# Where should we store stuff (downloaded episodes, rss database, &cet.)?
    store = os.path.expanduser('~/.local/share/potsy')
    if 'XDG_DATA_HOME' in os.environ :
        store = os.path.join(os.environ['XDG_DATA_HOME'],"potsy")
    if not os.path.isdir(store) :
        os.mkdir(store,0o600)

# Let's do this thing.
    curses.wrapper(interface)

if __name__ == "__main__":
    main()
